name: .venv-magnetometer
channels:
    - conda-forge
dependencies:
    - python=3.8
    - cycler=0.11.0
    - fonttools=4.33.3
    - kiwisolver=1.4.2
    - packaging=21.3
    - Pillow=9.1.1
    - pyparsing=3.0.9
    - python-dateutil=2.8.2
    - six=1.16.0
    - pip>=20.0.2
    - pip:
        - matplotlib==3.5.2
        - numpy==1.22.4
        - pyserial==3.5
